### ISSUE TITLE
bot died after creating a survey

### ISSUE THREAD

**Issue by R3V1EV** [pesaventofilippo/grouphelperbot#5]
Yesterday I created a poll, and the bot stopped responding to any commands at all, and even after deleting the poll and restarting the bot, it continues to write errors

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 1191, in get_from_telegram_server
    offset = max([relay_to_collector(update) for update in result]) + 1
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 1191, in <listcomp>
    offset = max([relay_to_collector(update) for update in result]) + 1
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 1172, in relay_to_collector
    'pre_checkout_query'])
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 68, in _find_first_key
    raise KeyError('No suggested keys %s in %s' % (str(keys), str(d)))
KeyError: "No suggested keys ['message', 'edited_message', 'channel_post', 'edited_channel_post', 'callback_query', 'inline_query', 'chosen_inline_result', 'shipping_query', 'pre_checkout_query'] in {'update_id': 199824450, 'poll': {'is_anonymous': True, 'allows_multiple_answers': False, 'type': 'regular', 'id': '5298988606646386709', 'is_closed': True, 'options': [{'voter_count': 6, 'text': '\u0414\u0430'}, {'voter_count': 6, 'text': '\u041d\u0435\u0442'}], 'question': '\u0412\u0430\u0441 \u0431\u0435\u0441\u0438\u0442 \u0425\u0430\u043e?', 'total_voter_count': 12}}"`

**Comment by pesaventofilippo** [comment]
Hi! Sorry, but this bot is out of development, and is lacking support for all new Telegram features (like polls).
I'm planning to entirely rewrite this bot one day, to make it work with all Telegram features and to improve security and reliability.
Meanwhile, you can fix this error by opening the link https://api.telegram.org/bot<YOUR_BOT_TOKEN>/getUpdates - this link resets the received messages for your bot, so it doesn't crash anymore while trying to read a message it cannot understand.

**Comment by R3V1EV** [comment]
Thank you very much, I will wait for this wonderful day
